/*
 * MsgUtils.h
 *
 *  Created on: Jun 5, 2023
 *      Author: Eric
 */

 #ifndef SRC_MSGUTILS_H_
 #define SRC_MSGUTILS_H_
 
 #include "xil_types.h"
 #include <string.h>
 
 // Returns the character generated by n x key presses.
 u8 ChooseChar(u8 key);
 
 // Adds a character to the buffer.
 void AddCharToBuffer(u8 *buf, u8 ch);
 
 // Deletes last character from the given buffer.
 void DeleteCharFromBuffer(u8 *buf);
 
 
 #endif /* SRC_MSGUTILS_H_ */
 